//@flow

import axios from 'axios';
import { createHashHistory } from 'history';

const history = createHashHistory();

let ip = "localhost";

/**
 * Service for handling login, register, userInformation and user-dropdown update/mounted()
 * Communicates with server/database
 */
class UserService {
    mountDropdown: Function = () => {};
    mountMap: Function = () => {};

    /**
     * Attempts to log in an user, response saves user-information, including a token
     * @param username
     * @param password
     * @param next (function to run after code returned successfully)
     */
    attemptLogin(username: string, password: string, next) {
        userService.postLogin(username, password).then(response => {
            if(this.error(response)){
                return this.error(response);
            }
            if(response != null) {
                localStorage.setItem("user_id", response.user.user_id);
                localStorage.setItem("username", response.user.username);
                localStorage.setItem("image", response.user.image);
                localStorage.setItem("first_name", response.user.first_name);
                localStorage.setItem("last_name", response.user.last_name);
                localStorage.setItem("email", response.user.email);
                localStorage.setItem("phone", response.user.phone);
                localStorage.setItem("contact_id", response.contact_id);
                localStorage.setItem("token", response.token);
                localStorage.setItem("artist_id", response.artist.artist_id);
                localStorage.setItem("artist_name", response.artist.artist_name);
                this.mountDropdown();
                next();
                return response;
            }
        });
    }

    /**
     * Generates a user based on artist-information added by event-organizer to an event
     * @param artistName
     * @param firstName
     * @param lastName
     * @param phone
     * @param email
     * @param contactId
     * @returns {response from db}
     */
    generateArtistUser(artistName: string, firstName: string, lastName: string, phone: string, email: string, contactId: number) {
        let organizer = `${this.getFirstName()} ${this.getLastName()}`;
        let username: string = artistName.replace(/\s/g, '').toLowerCase();
        return this.attemptRegisterArtist(username, this.generateRandomPassword(10), firstName, lastName, phone,
                                            email, contactId, organizer, artistName)
            .then(response => response.data);
    }

    /**
     * Generates a random rassword from artist-accounts generated by event-organizers
     * @param length
     * @returns {string}
     */
    generateRandomPassword(length: number) {
        let result           = '';
        let characters       = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
        let charactersLength = characters.length;
        for (let i = 0; i < length; i++ ) {
            result += characters.charAt(Math.floor(Math.random() * charactersLength));
        }
        return result;
    }

    /**
     * Attempts to register a user from artist
     * @param username
     * @param password
     * @param firstName
     * @param lastName
     * @param phone
     * @param email
     * @param contactId
     * @param organizer
     * @param artistName
     * @returns {*}
     */
    attemptRegisterArtist(username: string, password: string, firstName: string, lastName: string, phone: string,
                          email: string, contactId: number, organizer: string, artistName: string) {
        let data = {
            "username": username,
            "password": password,
            "email": email,
            "contact_id": contactId,
            "artist_name": artistName,
            "organizer": organizer,
            "first_name": firstName,
            "last_name": lastName,
            "phone": phone
        };
        return this
            .postArtistUser(data)
            .then(response => {
                if(this.error(response)){
                    return this.error(response);
                } else {
                    return true;
                }
            });
    }

    /**
     * Attempts to register a user
     * @param username
     * @param password
     * @param email
     * @param firstName
     * @param lastName
     * @param phone
     */
    attemptRegister(username: string, password: string, email: string, firstName: string, lastName: string, phone: string){
        let data = {
            "username": username,
            "password": password,
            "email": email,
            "first_name": firstName,
            "last_name": lastName,
            "phone": phone
        };
        userService
            .postUser(data)
            .then(response => {
                if(this.error(response)){
                    return this.error(response);
                }
                if(response.user != null) {
                    localStorage.setItem("user_id", response.user.user_id);
                    localStorage.setItem("username", response.user.username);
                    localStorage.setItem("image", response.user.image);
                    localStorage.setItem("first_name", response.user.first_name);
                    localStorage.setItem("last_name", response.user.last_name);
                    localStorage.setItem("email", response.user.email);
                    localStorage.setItem("phone", response.user.phone);
                    localStorage.setItem("contact_id", response.user.contact_id);
                    localStorage.setItem("token", response.token);
                    localStorage.setItem("artist_id", response.artist.artist_id);
                    localStorage.setItem("artist_name", response.artist.artist_name);
                    this.mountDropdown();
                    history.push("/");
                    return true;
                }
            });

    }

    /**
     * Updates user-information for a user
     * @param email
     * @param firstName
     * @param lastName
     * @param phone
     * @returns {Promise<AxiosResponse<T> | never>}
     */
    updateUser(email: string, firstName: string, lastName: string, phone: string) {
        let data = {
            "email": email,
            "first_name": firstName,
            "last_name": lastName,
            "phone": phone
        };
        return axios.put('http://' + ip +':4000/auth/id/' + this.getUserId() + '/user/user/' + userService.getUserId(), data, {
            'headers': {
                'x-access-token': this.getToken()
            }}).then(response => {
                if(this.error(response)){
                    return this.error(response);
                }
                return response.data;
            });
    }

    /**
     * Updates password for a user
     * @param password
     * @param newPassword
     * @returns {Promise<AxiosResponse<T> | never>}
     */
    updatePassword(password: string, newPassword: string) {
        return axios.put('http://' + ip +':4000/auth/id/' + this.getUserId() + '/user/user/' + this.getUserId() + '/password', {"password": password, "newPassword": newPassword, "username": this.getUsername()}, {
            'headers': {
                'x-access-token': this.getToken()
            }}).then(response => {
                if(this.error(response)){
                    return this.error(response);
                }
                return response.data;
            });
    }

    /**
     *
     * @returns {user_id}
     */
    getUserId(): number {
        return localStorage.getItem("user_id");
    }

    /**
     * Outdated
     * @returns {user_id}
     */
    getContactId(): number {
        return localStorage.getItem("user_id");
    }

    /**
     *
     * @returns {username}
     */
    getUsername(): string {
        return localStorage.getItem("username");
    }

    /**
     *
     * @returns {image}
     */
    getIamge() {
        return localStorage.getItem("image");
    }

    /**
     *
     * @returns {first_name}
     */
    getFirstName(): string {
        return localStorage.getItem("first_name");
    }

    /**
     *
     * @returns {last_name}
     */
    getLastName(): string {
        return localStorage.getItem("last_name");
    }

    /**
     *
     * @returns {email}
     */
    getEmail(): string {
        return localStorage.getItem("email");
    }

    /**
     *
     * @returns {phone}
     */
    getPhone(): string {
        return localStorage.getItem("phone");
    }

    /**
     *
     * @returns {token}
     */
    getToken() {
        return localStorage.getItem("token");
    }

    /**
     *
     * @returns {artist_id}
     */
    getArtistId(): number {
        return localStorage.getItem("artist_id");
    }

    /**
     *
     * @returns {artist_name}
     */
    getArtistName(): string {
        return localStorage.getItem("artist_name");
    }

    /**
     * Request to log in with username and password, called from attemptLogin
     * @param username
     * @param password
     * @returns {Promise<AxiosResponse<T>/error | never>} user-information and token or only error
     */
    postLogin(username: string, password: string) {
        let data = {
            "username": username,
            "password": password
        };
        return axios.post('http://' + ip + ':4000/auth/login', data).then(response => {
            if(this.error(response)){
                return this.error(response);
            }
            return response.data;
        });

    }

    /**
     * Gets updates user-information
     * @returns {Promise<AxiosResponse<T>/error | never>} error if it fails, updates localstorage instead if success
     */
    getUser() {
        return axios.get('http://' + ip + ':4000/auth/id/' + userService.getUserId() + "/user/user/" + userService.getUserId(), {
            'headers': {
                'x-access-token': this.getToken()
            }}).then(response => {
            if(this.error(response)){
                return this.error(response);
            }
            if (response.data.user != null) {
                localStorage.setItem("user_id", response.data.user.user_id);
                localStorage.setItem("username", response.data.user.username);
                localStorage.setItem("image", response.data.user.image);
                localStorage.setItem("first_name", response.data.user.first_name);
                localStorage.setItem("last_name", response.data.user.last_name);
                localStorage.setItem("email", response.data.user.email);
                localStorage.setItem("phone", response.data.user.phone);
                localStorage.setItem("contact_id", response.data.user.contact_id);
            }
        });
    }

    /**
     * Requests to register an user, called from attemptRegister
     * @param data
     * @returns {Promise<AxiosResponse<T> | never>/error}
     */
    postUser(data: Object) {
        return axios.post('http://' + ip +':4000/auth/register', data).then(response => {
            if(this.error(response)){
                return this.error(response);
            }
            return response.data;
        });
    }

    /**
     * Requests to register an user from artist, called from attemptRegisterArtist
     * @param data
     * @returns {Promise<AxiosResponse<T> | never>}
     */
    postArtistUser(data: Object) {
        return axios.post(`http://${ip}:4000/auth/register`, data, {
            'headers': {
                'x-access-token': this.getToken()
            }}).then(response => {
                if(this.error(response)){
                    return this.error(response);
                }
                return response.data;
            });
    }

    /**
     * Requests new token with current token
     * @returns {Promise<AxiosResponse<T> | never>} sets token
     */
    updateToken() {
        let data = {
            "user_id": localStorage.getItem("user_id"),
            "username": localStorage.getItem("username"),
            "token": localStorage.getItem("token")
        };
        return axios.post('http://' + ip +':4000/auth/id/' + this.getUserId() + '/user/token', data, {
            'headers': {
                'x-access-token': this.getToken()
            }}).then(response => {
                if(this.error(response)){
                    return this.error(response);
                }
                localStorage.setItem("token", response.data.token);
                return response.data;
            });
    }

    /**
     * Sets user-information to null, including token
     */
    logout() {
        localStorage.setItem("user_id", null);
        localStorage.setItem("username", null);
        localStorage.setItem("image", null);
        localStorage.setItem("first_name", null);
        localStorage.setItem("last_name", null);
        localStorage.setItem("email", null);
        localStorage.setItem("phone", null);
        localStorage.setItem("contact_id", null);
        localStorage.setItem("token", null);
        localStorage.setItem("artist_id", null);
        localStorage.setItem("artist_name", null);
    }

    /**
     * Sets artist-information
     * @param artist_id
     * @param artist_name
     */
    setArtist(artist_id: number, artist_name: string) {
        localStorage.setItem("artist_id", artist_id);
        localStorage.setItem("artist_name", artist_name);
    }

    /**
     * Checks if the current token in older than a minute, requests new token if true
     * Uses updateToken();
     */
    checkToken() {
        if(localStorage.getItem("token_time") != null) {
            if(new Date().getTime() - new Date(localStorage.getItem("token_time")).getTime() > 60000) {
                localStorage.setItem("token_time", (new Date()).toString());
                console.log("update token");
                this.updateToken();
            }
        } else {
            localStorage.setItem("token_time", (new Date()).toString());
            this.updateToken();
        }
    }

    /**
     * Checks if response is an error from token failure or unauthorized access
     * @param res
     * @param token
     * @returns {} data from response
     */
    error(res: Response, token: boolean) {
        if(!token && this.getUserId() !== "null") {
            this.checkToken();
        }
        if(res.data) {
            if(res.data.error) {
                if(res.data.error === "Token") {
                    this.logout();
                    this.mountDropdown();
                    history.push("/login");
                    return res.data;
                } else if(res.data.error === "Not authorized") {
                    history.push("/404");
                    return res.data;
                } else {
                    return res.data;
                }
            }
        } else if(res.error) {
            return res;
        }
        return false;
    }

    /**
     * Sets mountDropdown, the mounted() from the dropdown showing login/register/user-information
     * runs from the dropdown mounted
     * @param mountDropdown
     */
    setMountDropdown(mountDropdown: Function) {
        this.mountDropdown = mountDropdown;
    }

    /**
     * Runs mounted in dropdown in navbar
     */
    mountDropdown() {
        this.mountDropdown();
    }

    /**
     * Returns the username of an organizer id
     * @param contactId
     * @returns {Promise<R>|Promise<R|*>}
     */
    getOrganizerUsername(contactId: number) {
        return axios.get('http://localhost:4000/api/event/organizer/' + contactId)
            .then(response => {
                console.log("Hello!");
                return response.data})
            .catch(error => console.log(error.message));
    }
}

export let userService = new UserService();